### ISSUE TITLE
Make gatherMedia into a module?

### ISSUE THREAD

**Issue by arBalasquide** [arBalasquide/media_server#6]
To make code more organized and easier to read, I think it might be better to create a gathermedia.js module. Eventually, gatherMedia is going to grab more info such as file size, type, etc. so perhaps in the future it would be necessary to do so.

**Comment by christophergeiger3** [comment]
@arBalasquide Sounds like a plan to me! As long as the abstraction makes sense/looks good in the code right now, I think it's worthwhile. Otherwise, if it turns out `gatherMedia.js` would be too small to be its own module, we could always implement it in some other way (like as a function) and make it a module in a future commit.

**Comment by christophergeiger3** [comment]
Yeah, I just checked it out now. Yeah for sure, we should make it a module :+1:

**Comment by arBalasquide** [comment]
Made gatherMedia a module but theres still some code in the main.js that can still be implemented into the gathermedia.js file.

**Comment by arBalasquide** [comment]
Completed.
